import { IPGKPP_BG } from './constants';

export const THEMES = {
  light: {
    name: 'light',
    bg: '#f8fafc', surface: '#ffffff', surfaceHover: '#f1f5f9',
    border: '#e2e8f0', borderStrong: '#cbd5e1',
    text: '#1e293b', textSecondary: '#64748b', textMuted: '#94a3b8',
    inputBg: '#ffffff', inputBorder: '#cbd5e1',
    navActive: '#eef2ff', navActiveText: '#4f46e5', navInactive: 'transparent', navInactiveText: '#475569',
    headerBg: '#ffffff', sidebarBg: '#ffffff',
    modalBg: '#ffffff', modalOverlay: 'rgba(0,0,0,0.5)',
    tableHeaderBg: '#f8fafc', tableRowHover: '#f8fafc', tableBorder: '#f1f5f9',
    cardBg: '#ffffff', cardBorder: '#e2e8f0', statCardBg: '#ffffff',
    bannerBg: 'rgba(255,255,255,0.92)',
    dropdownBg: '#ffffff', dropdownHover: '#eef2ff', dropdownHoverText: '#4f46e5',
    btnSecondaryBg: '#f1f5f9', btnSecondaryBorder: '#e2e8f0', btnSecondaryText: '#334155', btnSecondaryHover: '#e2e8f0',
    contentBgOpacity: 0.25,
    sectionBg: '#f8fafc', sectionBorder: '#e2e8f0', divider: '#e2e8f0',
    iconBg: '#eef2ff', iconColor: '#4f46e5',
    maintenanceBg: '#fef3c7', maintenanceBorder: '#fde68a', maintenanceText: '#92400e',
    availableBg: '#f0fdf4', availableBorder: '#bbf7d0', availableText: '#166534',
    occupiedBg: '#fef2f2', occupiedBorder: '#fecaca', occupiedText: '#991b1b',
    infoBg: '#eff6ff', infoBorder: '#bfdbfe', infoText: '#1e40af',
    successBg: '#f0fdf4', successBorder: '#bbf7d0', successText: '#166534',
    warningBg: '#fef3c7', warningBorder: '#fde68a', warningText: '#92400e',
    bannerTitle: '#1e3a8a', bannerSubtitle: '#64748b',
    tabActiveBg: '#4f46e5', tabActiveText: '#ffffff', tabInactiveBg: '#f1f5f9', tabInactiveText: '#475569',
    tabInactiveHover: '#e2e8f0',
  },
  dark: {
    name: 'dark',
    bg: '#0f172a', surface: '#1e293b', surfaceHover: '#334155',
    border: '#334155', borderStrong: '#475569',
    text: '#f1f5f9', textSecondary: '#94a3b8', textMuted: '#64748b',
    inputBg: '#1e293b', inputBorder: '#475569',
    navActive: '#1e1b4b', navActiveText: '#a5b4fc', navInactive: 'transparent', navInactiveText: '#cbd5e1',
    headerBg: '#1e293b', sidebarBg: '#1e293b',
    modalBg: '#1e293b', modalOverlay: 'rgba(0,0,0,0.75)',
    tableHeaderBg: '#1e293b', tableRowHover: '#334155', tableBorder: '#334155',
    cardBg: '#1e293b', cardBorder: '#334155', statCardBg: '#1e293b',
    bannerBg: 'rgba(30,41,59,0.92)',
    dropdownBg: '#1e293b', dropdownHover: '#1e1b4b', dropdownHoverText: '#a5b4fc',
    btnSecondaryBg: '#334155', btnSecondaryBorder: '#475569', btnSecondaryText: '#e2e8f0', btnSecondaryHover: '#475569',
    contentBgOpacity: 0.08,
    sectionBg: '#1e293b', sectionBorder: '#334155', divider: '#334155',
    iconBg: '#1e1b4b', iconColor: '#a5b4fc',
    maintenanceBg: '#451a03', maintenanceBorder: '#78350f', maintenanceText: '#fbbf24',
    availableBg: '#052e16', availableBorder: '#14532d', availableText: '#4ade80',
    occupiedBg: '#450a0a', occupiedBorder: '#7f1d1d', occupiedText: '#fca5a5',
    infoBg: '#1e1b4b', infoBorder: '#312e81', infoText: '#a5b4fc',
    successBg: '#052e16', successBorder: '#14532d', successText: '#4ade80',
    warningBg: '#451a03', warningBorder: '#78350f', warningText: '#fbbf24',
    bannerTitle: '#a5b4fc', bannerSubtitle: '#94a3b8',
    tabActiveBg: '#4f46e5', tabActiveText: '#ffffff', tabInactiveBg: '#334155', tabInactiveText: '#cbd5e1',
    tabInactiveHover: '#475569',
  }
};

export const createStyles = (theme) => ({
  app: { display: 'flex', minHeight: '100vh', fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif", color: theme.text, backgroundColor: theme.bg, transition: 'background-color 0.3s ease, color 0.3s ease' },
  sidebar: { width: '260px', backgroundColor: theme.sidebarBg, borderRight: `1px solid ${theme.border}`, display: 'flex', flexDirection: 'column', position: 'fixed', top: 0, left: 0, height: '100vh', zIndex: 100, transition: 'transform 0.2s ease, background-color 0.3s ease' },
  sidebarMobile: { transform: 'translateX(-100%)' },
  sidebarOpen: { transform: 'translateX(0)' },
  sidebarHeader: { padding: '16px 10px', borderBottom: `1px solid ${theme.border}`, display: 'flex', alignItems: 'center', justifyContent: 'center' },
  sidebarLogo: { width: '220px', height: 'auto', objectFit: 'contain' },
  nav: { flex: 1, padding: '16px', display: 'flex', flexDirection: 'column', gap: '4px' },
  navItem: (isActive) => ({ width: '100%', display: 'flex', alignItems: 'center', gap: '12px', padding: '10px 12px', borderRadius: '8px', fontSize: '14px', fontWeight: 500, border: 'none', cursor: 'pointer', transition: 'all 0.15s', backgroundColor: isActive ? theme.navActive : theme.navInactive, color: isActive ? theme.navActiveText : theme.navInactiveText, textAlign: 'left' }),
  main: { flex: 1, marginLeft: '260px', display: 'flex', flexDirection: 'column', minWidth: 0 },
  mainNoSidebar: { marginLeft: 0 },
  header: { backgroundColor: theme.headerBg, borderBottom: `1px solid ${theme.border}`, padding: '8px 16px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', position: 'sticky', top: 0, zIndex: 50, transition: 'background-color 0.3s ease' },
  headerInstitution: { display: 'flex', alignItems: 'center', gap: '6px' },
  headerInstitutionLogo: { height: '32px', width: 'auto', objectFit: 'contain' },
  content: { flex: 1, padding: '24px 32px', overflowY: 'auto', position: 'relative' },
  contentBg: { position: 'absolute', inset: 0, backgroundImage: `url(${IPGKPP_BG})`, backgroundSize: 'cover', backgroundPosition: 'center', opacity: theme.contentBgOpacity, pointerEvents: 'none', zIndex: 0 },
  contentInner: { position: 'relative', zIndex: 1 },
  hamburger: { padding: '8px', border: 'none', backgroundColor: 'transparent', cursor: 'pointer', color: theme.textSecondary, borderRadius: '8px', display: 'none' },
  userMenuContainer: { position: 'relative' },
  userMenuBtn: { display: 'flex', alignItems: 'center', gap: '8px', padding: '6px 12px', border: `1px solid ${theme.border}`, borderRadius: '8px', backgroundColor: theme.surface, cursor: 'pointer', color: theme.textSecondary, transition: 'all 0.15s' },
  userAvatar: (size = 32) => ({ width: size, height: size, borderRadius: '50%', objectFit: 'cover', backgroundColor: theme.border, display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden', flexShrink: 0 }),
  avatarPlaceholder: (size = 32) => ({ width: size, height: size, borderRadius: '50%', backgroundColor: theme.border, display: 'flex', alignItems: 'center', justifyContent: 'center', color: theme.textMuted, flexShrink: 0 }),
  dropdown: { position: 'absolute', top: 'calc(100% + 8px)', right: 0, width: '224px', backgroundColor: theme.dropdownBg, borderRadius: '12px', boxShadow: '0 20px 25px -5px rgba(0,0,0,0.25)', border: `1px solid ${theme.border}`, padding: '8px', zIndex: 200 },
  dropdownItem: { width: '100%', display: 'flex', alignItems: 'center', gap: '10px', padding: '10px 12px', borderRadius: '8px', fontSize: '14px', border: 'none', cursor: 'pointer', backgroundColor: 'transparent', color: theme.text, textAlign: 'left', transition: 'all 0.15s' },
  dropdownLogout: { color: '#f87171' },
  divider: { height: '1px', backgroundColor: theme.divider, margin: '8px 0' },
  modal: { position: 'fixed', inset: 0, backgroundColor: theme.modalOverlay, display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000, padding: '16px' },
  modalContent: { backgroundColor: theme.modalBg, borderRadius: '16px', boxShadow: '0 25px 50px -12px rgba(0,0,0,0.4)', width: '100%', maxWidth: '448px', overflow: 'hidden' },
  modalContentLarge: { backgroundColor: theme.modalBg, borderRadius: '16px', boxShadow: '0 25px 50px -12px rgba(0,0,0,0.4)', width: '100%', maxWidth: '640px', overflow: 'hidden', maxHeight: '90vh' },
  modalContentXLarge: { backgroundColor: theme.modalBg, borderRadius: '16px', boxShadow: '0 25px 50px -12px rgba(0,0,0,0.4)', width: '100%', maxWidth: '900px', overflow: 'hidden', maxHeight: '90vh' },
  modalHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '16px 20px', borderBottom: `1px solid ${theme.border}` },
  modalBody: { padding: '20px', overflowY: 'auto', maxHeight: 'calc(90vh - 70px)' },
  input: { width: '100%', padding: '10px 16px', border: `1px solid ${theme.inputBorder}`, borderRadius: '8px', fontSize: '14px', outline: 'none', transition: 'border-color 0.15s, background-color 0.3s', boxSizing: 'border-box', backgroundColor: theme.inputBg, color: theme.text },
  btnPrimary: { width: '100%', padding: '10px 16px', backgroundColor: '#4f46e5', color: '#ffffff', border: 'none', borderRadius: '8px', fontSize: '14px', fontWeight: 600, cursor: 'pointer', transition: 'background-color 0.15s' },
  btnSecondary: { padding: '8px 16px', backgroundColor: theme.btnSecondaryBg, color: theme.btnSecondaryText, border: `1px solid ${theme.btnSecondaryBorder}`, borderRadius: '8px', fontSize: '13px', fontWeight: 500, cursor: 'pointer', transition: 'all 0.15s', display: 'flex', alignItems: 'center', gap: '6px' },
  btnDanger: { padding: '6px', border: 'none', backgroundColor: 'transparent', cursor: 'pointer', color: '#f87171', borderRadius: '6px' },
  badge: (status) => {
    const colors = {
      Pending: { bg: '#fef3c7', color: '#92400e', border: '#fde68a' },
      Arrived: { bg: '#dbeafe', color: '#1e40af', border: '#bfdbfe' },
      Collected: { bg: '#d1fae5', color: '#065f46', border: '#a7f3d0' },
      Overdue: { bg: '#fee2e2', color: '#991b1b', border: '#fecaca' },
      Maintenance: { bg: theme.maintenanceBg, color: theme.maintenanceText, border: theme.maintenanceBorder }
    };
    const c = colors[status] || colors.Pending;
    return { display: 'inline-flex', padding: '4px 10px', borderRadius: '9999px', fontSize: '12px', fontWeight: 600, backgroundColor: c.bg, color: c.color, border: `1px solid ${c.border}` };
  },
  card: { backgroundColor: theme.cardBg, borderRadius: '12px', border: `1px solid ${theme.cardBorder}`, overflow: 'hidden', position: 'relative', zIndex: 1, transition: 'background-color 0.3s ease, border-color 0.3s ease' },
  statCard: { backgroundColor: theme.statCardBg, padding: '16px', borderRadius: '12px', border: `1px solid ${theme.cardBorder}`, position: 'relative', zIndex: 1, transition: 'background-color 0.3s ease' },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: '14px' },
  th: { padding: '12px 16px', textAlign: 'left', fontWeight: 600, color: theme.textSecondary, backgroundColor: theme.tableHeaderBg, borderBottom: `1px solid ${theme.border}`, fontSize: '12px', textTransform: 'uppercase', letterSpacing: '0.05em' },
  td: { padding: '12px 16px', borderBottom: `1px solid ${theme.tableBorder}`, color: theme.text },
  pagination: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginTop: '16px', paddingTop: '16px', borderTop: `1px solid ${theme.border}`, position: 'relative', zIndex: 1 },
  pageBtn: (active) => ({ width: '32px', height: '32px', display: 'flex', alignItems: 'center', justifyContent: 'center', borderRadius: '8px', border: active ? 'none' : `1px solid ${theme.border}`, backgroundColor: active ? '#4f46e5' : theme.surface, color: active ? '#ffffff' : theme.text, fontSize: '14px', fontWeight: 500, cursor: 'pointer' }),
  overlay: { position: 'fixed', inset: 0, backgroundColor: 'rgba(0,0,0,0.4)', zIndex: 99 },
  pageBanner: { position: 'relative', zIndex: 1, display: 'flex', alignItems: 'center', gap: '16px', padding: '12px 20px', marginBottom: '20px', backgroundColor: theme.bannerBg, borderRadius: '12px', border: `1px solid ${theme.border}`, backdropFilter: 'blur(8px)', transition: 'background-color 0.3s ease' },
  bannerLogo: { height: '48px', width: 'auto', objectFit: 'contain' },
  bannerText: { display: 'flex', flexDirection: 'column' },
  bannerTitle: { fontSize: '14px', fontWeight: 700, color: theme.bannerTitle, margin: 0, letterSpacing: '0.025em' },
  bannerSubtitle: { fontSize: '10px', color: theme.bannerSubtitle, margin: 0, marginTop: '2px' },
  scannerContainer: { width: '100%', maxWidth: '400px', margin: '0 auto', borderRadius: '12px', overflow: 'hidden', backgroundColor: '#000', position: 'relative' },
  scannerOverlay: { position: 'absolute', inset: 0, border: '3px solid #4f46e5', borderRadius: '12px', pointerEvents: 'none' },
  scannerLine: { position: 'absolute', left: '10%', right: '10%', height: '2px', backgroundColor: '#4f46e5', boxShadow: '0 0 10px #4f46e5', animation: 'scanline 2s ease-in-out infinite' },
  scanSuccess: { display: 'flex', alignItems: 'center', gap: '8px', padding: '12px 16px', backgroundColor: theme.successBg, border: `1px solid ${theme.successBorder}`, borderRadius: '8px', color: theme.successText, fontSize: '14px', fontWeight: 500, marginTop: '12px' },
  profilePicUpload: { display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '12px', padding: '20px' },
  profilePicPreview: { width: '100px', height: '100px', borderRadius: '50%', objectFit: 'cover', backgroundColor: theme.border, display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden', border: `3px solid ${theme.border}`, transition: 'border-color 0.2s' },
  profilePicPlaceholder: { width: '100px', height: '100px', borderRadius: '50%', backgroundColor: theme.border, display: 'flex', alignItems: 'center', justifyContent: 'center', color: theme.textMuted, border: `3px dashed ${theme.borderStrong}` },
  uploadBtn: { padding: '8px 20px', backgroundColor: theme.inputBg, color: '#4f46e5', border: `1px solid #4f46e5`, borderRadius: '8px', fontSize: '13px', fontWeight: 500, cursor: 'pointer', transition: 'all 0.15s', display: 'flex', alignItems: 'center', gap: '6px' },
  removePicBtn: { padding: '6px 12px', backgroundColor: '#fef2f2', color: '#dc2626', border: '1px solid #fecaca', borderRadius: '6px', fontSize: '12px', cursor: 'pointer', transition: 'all 0.15s' },
  themeToggle: { padding: '8px', border: `1px solid ${theme.border}`, borderRadius: '8px', backgroundColor: theme.btnSecondaryBg, cursor: 'pointer', color: theme.textSecondary, transition: 'all 0.15s', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  themeToggleHover: { backgroundColor: theme.btnSecondaryHover },
});